site_name: Javier Alejandro Oramas Lopez
site_url: https://javieroramas.github.io
repo_url: https://github.com/javieroramas
edit_uri: ""

theme:
  name: material
  logo: assets/images/avatar.jpg
  favicon: assets/images/avatar.jpg
  features:
    # - navigation.instant
    - navigation.tabs
  palette:
    primary: black
    accent: light blue

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - meta
  - toc:
      permalink: 🔗

google_analytics:
  - G-1ZVVREL82C
  - auto

nav:
  - Home:
    - Intro: index.md
    - Blog 📝: ./blog
  - Blog 📝:
    - Last Posts: blog/index.md
    - LaLuu: blog/LaLuu/index.md


copyright: Copyright &copy; Javier Alejandro Oramas Lopez

extra:
  disqus: javier
  manifest: manifest.json
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/javier-alejandro-oramas-l%C3%B3pez-7ab47b160/
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/javieroramas
      name: GitHub
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/javiale2000
      name: GitLab
    - icon: fontawesome/solid/code
      link: https://profile.codersrank.io/user/javieroramas
      name: Codersrank
    - icon: fontawesome/brands/dev
      link: https://dev.to/javieroramas
      name: Dev.to
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/10792685/javier-alejandro-oramas-l%c3%b3pez
      name: Stack Overflow
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Javier_Oramas
      name: Research Gate
    - icon: fontawesome/brands/medium
      link: https://medium.com/@javiale2000
      name: Medium
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/javi_oramas
      name: Twitter
    - icon: fontawesome/brands/telegram
      link: https://t.me/JOramas
      name: Telegram
    - icon: fontawesome/solid/paper-plane
      link: mailto:javiale2000@gmail.com
      name: Gmail
